conky.config = {
  alignment = 'top_right',
  gap_x = 40, gap_y = 60,
  minimum_width = 320, maximum_width = 320,

  update_interval = 1,
  cpu_avg_samples = 2,
  double_buffer = true,
  imlib_cache_size = 2097152,

  own_window = true,
  own_window_type = 'desktop',
  own_window_class = 'ConkyHUD',
  own_window_transparent = false,
  own_window_argb_visual = true,
  own_window_argb_value = 215,
  own_window_colour = '171520',
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

  draw_borders = true,
  border_width = 1,
  border_inner_margin = 14,
  draw_shades = false,
  draw_outline = false,

  use_xft = true,
  font = 'Space Mono:size=9',
  default_color = '8a6bd1',   -- borda e barras (lilac)
  color1 = 'fbfbfb',          -- texto
  color2 = 'c9b6f2',          -- titulos (lilac-soft)
  color3 = 'ff9fc7',          -- destaques (pink)
  default_bar_height = 6,
}

conky.text = [[
${font VT323:size=18}${color2}HUD // SYSTEM LOAD${alignr}${color3}● ONLINE${font}
${color}${hr 1}
${color1}CPU ${alignr}${cpu cpu0}%
${color}${cpubar 6,292}
${color1}GPU ${alignr}${execi 2 ~/.config/conky/hud.sh gpu_use}%
${color}${execibar 2 ~/.config/conky/hud.sh gpu_use}
${color1}RAM ${alignr}${memperc}%
${color}${membar 6,292}
${color1}DISCO ${alignr}${fs_used_perc /}%
${color}${fs_bar 6,292 /}

${color2}CPU TEMP ${alignr}${color3}${execi 5 ~/.config/conky/hud.sh cpu_temp}°C
${color2}GPU TEMP ${alignr}${color3}${execi 5 ~/.config/conky/hud.sh gpu_temp}°C
${color2}UPTIME   ${alignr}${color3}${uptime_short}

${color}${hr 1}
${image ~/.config/conky/star.png -p 29,326 -s 52x52 -f 3600}${alignc -34}${font VT323:size=46}${color2}${time %H:%M:%S}${font}
${alignc -34}${color1}${time %Y.%m.%d}${color} // ${color3}${time %A}
]]
